"""Tool to push branch and create a pull request via gh CLI."""

import logging
import re
import os
import subprocess
import tempfile
from typing import Any

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


def _make_pr_body(
    task: str,
    implementation: str,
    plan: str = "",
    review_verdict: str = "",
    issue_url: str = "",
    issue_id: str = "",
) -> str:
    """Build PR body markdown."""
    parts = [f"## Task\n{task or '(no task)'}\n"]
    if issue_url:
        parts.append(f"**Issue:** {issue_url}\n")
    if issue_id:
        parts.append(f"**Closes:** {issue_id}\n")
    impl = (implementation or "").strip()
    if impl:
        preview = impl[:1200] + ("..." if len(impl) > 1200 else "")
        parts.append(f"## Implementation Summary\n{preview}\n")
    plan_str = (plan or "").strip()
    if plan_str:
        plan_preview = plan_str[:800] + ("..." if len(plan_str) > 800 else "")
        parts.append(f"## Plan\n{plan_preview}\n")
    verdict = (review_verdict or "").strip()
    if verdict and verdict.upper().startswith("APPROVED"):
        parts.append("## Review\n✅ APPROVED\n")
    parts.append("\n_Generated by code_pipeline_")
    return "\n".join(parts)


class CreatePRToolInput(BaseModel):
    """Input schema for CreatePRTool."""

    feature_branch: str = Field(..., description="Feature branch to push")
    base_branch: str = Field(..., description="Base branch (e.g. main)")
    task: str = Field(..., description="Task description for PR title and body")
    implementation: str = Field(default="", description="Implementation summary")
    plan: str = Field(default="", description="Plan summary")
    review_verdict: str = Field(default="", description="Review verdict (APPROVED or ISSUES)")
    issue_url: str = Field(default="", description="Issue URL link")
    issue_id: str = Field(default="", description="Issue ID (e.g. fixes #42)")
    github_repo: str = Field(..., description="GitHub repo owner/name for gh")
    labels: str = Field(default="", description="Comma-separated PR labels (e.g. feat, fix)")


class CreatePRTool(BaseTool):
    """Push the feature branch and create a PR via gh CLI."""

    name: str = "Create PR Tool"
    description: str = (
        "Push the feature branch to origin and create a pull request using gh CLI. "
        "Requires: feature_branch, base_branch, task, github_repo. "
        "Optional: implementation, plan, review_verdict, issue_url, issue_id, labels."
    )
    args_schema: type[BaseModel] = CreatePRToolInput

    repo_path: str = ""

    def _run(
        self,
        feature_branch: str,
        base_branch: str,
        task: str,
        implementation: str = "",
        plan: str = "",
        review_verdict: str = "",
        issue_url: str = "",
        issue_id: str = "",
        github_repo: str = "",
        labels: str = "",
        **kwargs: Any,
    ) -> str:
        repo = os.path.abspath(self.repo_path or os.getcwd())
        if not os.path.isdir(repo):
            return f"Error: repo_path does not exist: {repo}"
        github_repo = (github_repo or "").strip()
        if not github_repo:
            return "Error: github_repo is required to create a PR"

        logger.info("Publishing branch %s to origin", feature_branch)
        try:
            push = subprocess.run(
                ["git", "push", "-u", "origin", feature_branch],
                cwd=repo,
                capture_output=True,
                text=True,
                timeout=60,
            )
            if push.returncode != 0 and "already exists" not in (push.stderr or ""):
                logger.warning("git push failed: %s", push.stderr or push.stdout)
                return f"Branch not pushed: {push.stderr or push.stdout}"
        except Exception as e:
            logger.error("git push failed: %s", e, exc_info=True)
            return f"Failed to push: {e}"

        title = task.strip().split("\n")[0][:80] if task else "Code changes"
        body = _make_pr_body(
            task, implementation, plan, review_verdict, issue_url, issue_id
        )
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".md", delete=False
            ) as f:
                f.write(body)
                body_file = f.name
            try:
                result = subprocess.run(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--base",
                        base_branch,
                        "--head",
                        feature_branch,
                        "--title",
                        title,
                        "--body-file",
                        body_file,
                    ],
                    cwd=repo,
                    capture_output=True,
                    text=True,
                    timeout=30,
                    env={**os.environ, "GH_REPO": github_repo},
                )
                if result.returncode != 0:
                    logger.warning(
                        "gh pr create failed: %s", result.stderr or result.stdout
                    )
                    return f"PR creation failed: {result.stderr or result.stdout}"
                pr_url = (result.stdout or "").strip()
                if pr_url:
                    print(f"\n🔗 PR opened: {pr_url}\n")

                # Add labels if provided
                label_list = [x.strip() for x in (labels or "").split(",") if x.strip()]
                if label_list and pr_url:
                    try:
                        match = re.search(r"/pull/(\d+)", pr_url)
                        if match:
                            pr_number = match.group(1)
                            for lbl in label_list:
                                subprocess.run(
                                    ["gh", "pr", "edit", pr_number, "--add-label", lbl],
                                    cwd=repo,
                                    capture_output=True,
                                    text=True,
                                    timeout=15,
                                    env={**os.environ, "GH_REPO": github_repo},
                                )
                            logger.info("Labels added: %s", label_list)
                    except Exception as e:
                        logger.warning("Failed to add labels: %s", e)

                return pr_url or "PR created"
            finally:
                os.unlink(body_file)
        except FileNotFoundError:
            logger.warning("gh CLI not found; install from https://cli.github.com")
            return "gh CLI not found; install to create PRs"
        except Exception as e:
            logger.error("gh pr create failed: %s", e, exc_info=True)
            return f"PR creation failed: {e}"
