"""Tool to push branch and create a pull request via gh CLI."""

import logging
import re
import os
import subprocess
import tempfile
from typing import Any

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


def _make_pr_body(
    task: str,
    implementation: str,
    plan: str = "",
    review_verdict: str = "",
    issue_url: str = "",
    issue_id: str = "",
) -> str:
    """Build PR body markdown."""
    if task:
        task_display = task
    else:
        task_display = "(no task)"
    parts = [f"## Task\n{task_display}\n"]
    if issue_url:
        parts.append(f"**Issue:** {issue_url}\n")
    if issue_id:
        parts.append(f"**Closes:** {issue_id}\n")
    if implementation is not None:
        impl = implementation.strip()
    else:
        impl = ""
    if impl:
        if len(impl) > 1200:
            preview = impl[:1200] + "..."
        else:
            preview = impl
        parts.append(f"## Implementation Summary\n{preview}\n")
    if plan is not None:
        plan_str = plan.strip()
    else:
        plan_str = ""
    if plan_str:
        if len(plan_str) > 800:
            plan_preview = plan_str[:800] + "..."
        else:
            plan_preview = plan_str
        parts.append(f"## Plan\n{plan_preview}\n")
    if review_verdict is not None:
        verdict = review_verdict.strip()
    else:
        verdict = ""
    if verdict and verdict.upper().startswith("APPROVED"):
        parts.append("## Review\n✅ APPROVED\n")
    parts.append("\n_Generated by code_pipeline_")
    return "\n".join(parts)


class CreatePRToolInput(BaseModel):
    """Input schema for CreatePRTool."""

    feature_branch: str = Field(..., description="Feature branch to push")
    base_branch: str = Field(..., description="Base branch (e.g. main)")
    task: str = Field(..., description="Task description for PR title and body")
    implementation: str = Field(default="", description="Implementation summary")
    plan: str = Field(default="", description="Plan summary")
    review_verdict: str = Field(
        default="", description="Review verdict (APPROVED or ISSUES)"
    )
    issue_url: str = Field(default="", description="Issue URL link")
    issue_id: str = Field(default="", description="Issue ID (e.g. fixes #42)")
    github_repo: str = Field(..., description="GitHub repo owner/name for gh")
    labels: str = Field(
        default="", description="Comma-separated PR labels (e.g. feat, fix)"
    )


class CreatePRTool(BaseTool):
    """Push the feature branch and create a PR via gh CLI."""

    name: str = "Create PR Tool"
    description: str = (
        "Push the feature branch to origin and create a pull request using gh CLI. "
        "Requires: feature_branch, base_branch, task, github_repo. "
        "Optional: implementation, plan, review_verdict, issue_url, issue_id, labels."
    )
    args_schema: type[BaseModel] = CreatePRToolInput

    repo_path: str = ""

    def _run(
        self,
        feature_branch: str,
        base_branch: str,
        task: str,
        implementation: str = "",
        plan: str = "",
        review_verdict: str = "",
        issue_url: str = "",
        issue_id: str = "",
        github_repo: str = "",
        labels: str = "",
        **kwargs: Any,
    ) -> str:
        rp = self.repo_path
        if rp is None or rp == "":
            rp = os.getcwd()
        repo = os.path.abspath(rp)
        if not os.path.isdir(repo):
            return f"Error: repo_path does not exist: {repo}"
        if github_repo is not None:
            github_repo = github_repo.strip()
        else:
            github_repo = ""
        if not github_repo:
            logger.info("└─[ CreatePRTool FAILED ]─ github_repo is required")
            return "Error: github_repo is required to create a PR"

        logger.info("┌─[ CreatePRTool EXECUTE ]─")
        logger.info("│ Input:")
        logger.info("│   Feature branch: %s", feature_branch)
        logger.info("│   Base branch: %s", base_branch)
        logger.info("│   GitHub repo: %s", github_repo)
        if len(task) > 100:
            task_preview = task[:100] + "..."
        else:
            task_preview = task
        logger.info("│   Task: %s", task_preview)
        if issue_id:
            issue_id_display = issue_id
        else:
            issue_id_display = "(none)"
        logger.info("│   Issue ID: %s", issue_id_display)
        if labels:
            labels_display = labels
        else:
            labels_display = "(none)"
        logger.info("│   Labels: %s", labels_display)
        logger.info("│ Publishing branch %s to origin", feature_branch)
        try:
            push = subprocess.run(
                ["git", "push", "-u", "origin", feature_branch],
                cwd=repo,
                capture_output=True,
                text=True,
                timeout=60,
            )
            push_err = push.stderr if push.stderr is not None else ""
            if push.returncode != 0 and "already exists" not in push_err:
                if push.stderr:
                    log_msg = push.stderr
                else:
                    log_msg = push.stdout if push.stdout is not None else ""
                logger.warning("git push failed: %s", log_msg)
                logger.info("└─[ CreatePRTool FAILED ]─ git push failed")
                if push.stderr is not None and push.stderr != "":
                    err_display = push.stderr
                elif push.stdout is not None:
                    err_display = push.stdout
                else:
                    err_display = ""
                return f"Branch not pushed: {err_display}"
        except Exception as e:
            logger.error("git push failed: %s", e, exc_info=True)
            logger.info("└─[ CreatePRTool FAILED ]─ git push failed")
            return f"Failed to push: {e}"

        if task:
            title = task.strip().split("\n")[0][:80]
        else:
            title = "Code changes"
        body = _make_pr_body(
            task, implementation, plan, review_verdict, issue_url, issue_id
        )
        try:
            with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
                f.write(body)
                body_file = f.name
            try:
                result = subprocess.run(
                    [
                        "gh",
                        "pr",
                        "create",
                        "--base",
                        base_branch,
                        "--head",
                        feature_branch,
                        "--title",
                        title,
                        "--body-file",
                        body_file,
                    ],
                    cwd=repo,
                    capture_output=True,
                    text=True,
                    timeout=30,
                    env={**os.environ, "GH_REPO": github_repo},
                )
                if result.returncode != 0:
                    if result.stderr:
                        err_msg = result.stderr
                    else:
                        err_msg = result.stdout if result.stdout is not None else ""
                    logger.warning("gh pr create failed: %s", err_msg)
                    logger.info("└─[ CreatePRTool FAILED ]─ gh pr create failed")
                    return f"PR creation failed: {err_msg}"
                stdout_val = result.stdout
                if stdout_val is not None:
                    pr_url = stdout_val.strip()
                else:
                    pr_url = ""
                if pr_url:
                    print(f"\n🔗 PR opened: {pr_url}\n")
                    logger.info("│ PR URL: %s", pr_url)

                # Add labels if provided
                labels_val = labels if labels is not None else ""
                label_list = [x.strip() for x in labels_val.split(",") if x.strip()]
                if label_list and pr_url:
                    try:
                        match = re.search(r"/pull/(\d+)", pr_url)
                        if match:
                            pr_number = match.group(1)
                            logger.info("│ Adding labels: %s", ", ".join(label_list))
                            for lbl in label_list:
                                subprocess.run(
                                    ["gh", "pr", "edit", pr_number, "--add-label", lbl],
                                    cwd=repo,
                                    capture_output=True,
                                    text=True,
                                    timeout=15,
                                    env={**os.environ, "GH_REPO": github_repo},
                                )
                            logger.info("│ Labels added successfully")
                    except Exception as e:
                        logger.warning("Failed to add labels: %s", e)

                logger.info("└─[ CreatePRTool COMPLETE ]─")
                return pr_url or "PR created"
            finally:
                os.unlink(body_file)
        except FileNotFoundError:
            logger.warning("gh CLI not found; install from https://cli.github.com")
            logger.info("└─[ CreatePRTool FAILED ]─ gh CLI not found")
            return "gh CLI not found; install to create PRs"
        except Exception as e:
            logger.error("gh pr create failed: %s", e, exc_info=True)
            logger.info("└─[ CreatePRTool FAILED ]─")
            return f"PR creation failed: {e}"
